export const TIMINGS = {
  UPLOAD: {
    PROGRESS_INTERVAL: 200,
    COMPLETION_DELAY: 3000
  },
  PREVIEW: {
    READY_DELAY: 2000
  },
  MOCK: {
    CONFIG_DELAY: 1000,
    PARAM_DELAY: 2000,
    COMPLETE_DELAY: 3000
  }
} as const; 