export const COMMANDS = {
  LOGO: {
    TITLE: 'ARCHIMETERS',
    SUBTITLE: 'PARAMETRIC TERMINAL'
  },
  HELP: {
    TITLE: 'AVAILABLE COMMANDS',
    QUICK_REFERENCE: 'QUICK REFERENCE'
  }
} as const; 