export const archimeters = [
    '\x1b[38;2;255;199;143mAbout & Vision',
    'Archimeters started from an idea in a Computational Design class',
    'in architecture school. The professor talked about how',
    'parametric design can make buildings smarter, use less material,',
    'and be more eco-friendly. That made us wonder: what if these',
    'design ideas could go on-chain? Could more people join in, and',
    'could designers share their algorithms with everyone? Maybe NFTs',
    'could be more than just collectibles—they could be interactive,',
    'creative and even useful.',
    '',
    'With a curious and experimental spirit, we wanted to use the Sui',
    'tech stack to build an open and fun platform.Designers can share',
    'their own design algorithms, and anyone can play with the',
    "parameters to make their own version. Here, it's not just about",
    "collecting art—it's about joining in, creating together, and",
    'even making things you can use in real life.',
    '',
    'We hope this project can be a playground for designers,',
    'collectors, makers, and anyone who likes design. Maybe one day,',
    'digital design and making things will feel as easy and fun as',
    'playing a game. This small experiment is just our first step.',
    '',
]