export const COMMANDS = {
  LOGO: {
    TITLE: 'ARCHIMETERS DESIGN LAB',
    SUBTITLE: 'PARAMETRIC TERMINAL'
  },
  HELP: {
    TITLE: 'COMMAND INTERFACE',
    QUICK_REFERENCE: 'QUICK REFERENCE'
  }
} as const; 